# Generated by Django 5.1.4 on 2025-01-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponggame',
            old_name='creatd_date',
            new_name='created_date',
        ),
    ]
