# Generated by Django 5.1.4 on 2025-01-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_creatd_date_ponggame_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpsgame',
            old_name='creatd_date',
            new_name='created_date',
        ),
    ]
