# Generated by Django 5.1.4 on 2025-01-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_creatd_date_rpsgame_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpsgame',
            old_name='pong_id',
            new_name='rps_id',
        ),
    ]
