services:
  be:
    build:
      context: be
      dockerfile: dockerfile
    container_name: be
    env_file:
      - be/.env
    ports:
      - "8081:8081"
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8081"]
    working_dir: /app
    volumes:
      - ./be:/app
    networks:
      - nw
    depends_on:
      - db

  fe:
    build:
      context: fe
      dockerfile: dockerfile
    container_name: fe
    env_file:
      - fe/.env
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./fe:/app
    networks:
      - nw

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - be/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nw

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - nw

volumes:
  postgres_data:

networks:
  nw:
    driver: bridge