# Generated by Django 5.1.4 on 2025-01-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='refresh_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
