# Generated by Django 5.1.4 on 2025-01-10 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_refresh_token'),
        ('user', '0002_users_access_token_users_rsp_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('pong_id', models.AutoField(primary_key=True, serialize=False)),
                ('creatd_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('winner_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loser_score', models.PositiveIntegerField(blank=True, null=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_lost', to='user.users')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='user.users')),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
