# Generated by Django 5.1.4 on 2025-01-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ponggame_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PongGame',
        ),
    ]
