# Generated by Django 5.1.4 on 2025-01-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_ponggame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
