# Generated by Django 5.1.4 on 2025-01-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_access_token_users_rsp_draw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='rsp_draw',
            new_name='rps_draw',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='rsp_lose',
            new_name='rps_lose',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='rsp_win',
            new_name='rps_win',
        ),
    ]
