# Generated by Django 5.1.4 on 2025-01-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_rsp_draw_users_rps_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
