# Generated by Django 5.1.4 on 2025-01-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
