# Generated by Django 5.1.4 on 2025-01-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_users_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='jwt_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
