# Generated by Django 5.1.4 on 2025-01-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_users_jwt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
